### ISSUE TITLE
needed update for icons (+ other parts of manifest)

### ISSUE THREAD

**Issue by jakswa** [jakswa/marta_ui#17]
I think something changed with android recently, and it caused me to run the lighthouse PWA audit again. I discovered a couple edits being needed:
- Web app manifest does not meet the installability requirements
  Failures: Manifest does not have a PNG icon of at least 192px.
- Does not provide a valid apple-touch-icon 
For ideal appearance on iOS when users add to the home screen, define an apple-touch-icon. It must point to a non-transparent 192px (or 180px) square PNG

in image forms:
![image](https://user-images.githubusercontent.com/137793/63071625-0791cb80-beee-11e9-9206-5bec55ea5644.png)
![image](https://user-images.githubusercontent.com/137793/63071665-38720080-beee-11e9-9853-a737ae061fb2.png)

**Comment by jakswa** [comment]
Here are the two original design assets I have for this, if new icon resolutions are needed:

![icon-01](https://user-images.githubusercontent.com/137793/66168202-95468900-e60a-11e9-8288-908d9c4602a3.png)
![logoFinal-02](https://user-images.githubusercontent.com/137793/66168203-95df1f80-e60a-11e9-93e6-fe50af6d7d63.png)

**Comment by Larsklopstra** [comment]
I opened a PR! 😄
