### ISSUE TITLE
dark theme

### ISSUE THREAD

**Issue by jakswa** [jakswa/marta_ui#19]
Requested by a user in gitter:
> May we have a dark mode?

I think this could be a toggle-able setting stored in localstorage, adds a root class that switches up colors maybe? I have never done a dark theme, only imagining how it'd go. Maybe there is a more standard way that is more maintainable, found by:
- searching materiul UI docs (this UI uses the react material UI at https://material-ui.com/)
- searching for other react or PWA examples of dark themes

**Comment by Magvin** [comment]
Hi. Can you assign this to me?

**Comment by jakswa** [comment]
Thanks @Magvin! I did find mention of dark/light in the material UI docs, in case it helps: https://material-ui.com/customization/palette/#type-light-dark-theme

**Comment by jakswa** [comment]
linking this to https://github.com/jakswa/marta_ui/pull/20, since it should fix this

**Comment by jakswa** [comment]
deployed this!
