### ISSUE TITLE
(chrome only) get "add to homescreen" functionality back

### ISSUE THREAD

**Issue by jakswa** [jakswa/marta_ui#22]
Since launching this a year+ ago, Chrome [switched up the add-to-homescreen requirements](https://love2dev.com/blog/beforeinstallprompt/). If I were to use `create-react-app` today, I believe it has recommendations involving the new `beforeinstallprompt` hooks.

New requirements:
- listen to `beforeinstallprompt`, when it occurs...
- we have to show our own "add to homescreen" UI (maybe just a sliver of a line item at top of the page, using a standard material-ui.com component -- this would be dismiss-able if the user doesn't care to add-to-homescreen
- if the user opts into it, there's a system prompt that occurs. It's described in the link above as well as [this section](https://developers.google.com/web/fundamentals/app-install-banners)

**Comment by silltho** [comment]
i think you don't have to listen to the beforeinstallpromt event. 

for a local test you should do a production build ```npm run build``` and serve it with ```serve -s build```. 
https://github.com/jakswa/marta_ui/blob/35b24b1da0e4f6c213105e39816bf47874349fa0/src/registerServiceWorker.js#L26

![image](https://user-images.githubusercontent.com/5812228/66264897-4157c200-e80d-11e9-8b7f-7c88889b7d87.png)
https://create-react-app.dev/docs/making-a-progressive-web-app

I did this last week in one of my project and it was enough to get the default add to homescreen prompt.

**Comment by jakswa** [comment]
Thanks @silltho, that's good perspective. For some reason I thought Chrome was deprecating the old way, but now it looks like they just added an alternate path.

I'll close this and hope I never need to reopen :crossed_fingers:

**Comment by jakswa** [comment]
Verified the mini bar works still at least:
![Screenshot_20191006-111640](https://user-images.githubusercontent.com/137793/66271341-ec2aa900-e82a-11e9-8844-b9e850ceac05.png)
